name: ML Training and Inference

on:
  workflow_dispatch:
  #push:
    #branches: [ "sess_06_mnist" ]

jobs:
  train-and-infer:
    runs-on: ubuntu-latest
    
    steps:
    # Step to checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run training
      run: |
        python src/train.py
        
    - name: Save model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: |
          models/*.pt
        retention-days: 7
        
    
    - name: Run inference
      run: |
        python src/infer.py
        
    - name: Save inference results
      uses: actions/upload-artifact@v3
      with:
        name: inference-results
        path: |
          inference_results/random_samples/*.png
          inference_results/random_samples/*.json
          inference_results/*.txt
        retention-days: 7
        
    
